### PR TITLE
Can has PlayFab?

### PR DESCRIPTION
**Pull request by skylarjhdownes**
Stuff from yesterday.

### CODE REVIEW

**Comment by skylarjhdownes** [comment]
Is there a way to attach the Issue/bug to this?  I suppose I can just link it: https://github.com/ehgoodenough/papercut/issues/74

**Comment by ehgoodenough** [comment]
Yup! If you just type the number, just like you did, it'll link it to the issue. That's why PRs and Issues share the same numbering system.

**Comment by ehgoodenough** [comment]
I'm currently debating whether to merge this; now that the hackathon is over, I just don't care about PlayFab anymore. Hrmmm..

**Comment by skylarjhdownes** [comment]
I suppose I ought to pull the bugfixes off into their own branch so we can merge them separately.  Can I do that locally and then just push, or is it more in depth than that?  I am still a branching newb.

**Comment by ehgoodenough** [comment]
Yeah, you could `git checkout -b my-new-branch`, but I think it'd just be easier to merge this, and then just ignore the PlayFab stuff unless we need it, you know?

**Pull request merged**
